package com.vizuri.fhir;
import org.hl7.fhir.dstu3.model.RiskAssessment;
import org.hl7.fhir.dstu3.model.Patient;
import java.time.LocalDate;
import java.time.Period;
import java.time.ZoneId;
import java.lang.Double;
import org.hl7.fhir.dstu3.model.RiskAssessment;
//add the imports for the conversion 



rule "Init"
salience 999
when
    p: Patient( )
then
    //Score 
    Points points = new Points();
    points.setPointTotal(0.0);
    insert (points);
    PatientAge age = new PatientAge();
    insert (age);
    
    System.out.println("Start here INIT 55");
    
    
    
    LocalDate birthdate = p.getBirthDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
    LocalDate today = LocalDate.now();
    Period period = Period.between(birthdate, today);
    age.setAge(period.getYears());
    
end

