package com.vizuri.fhir;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Final implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.Double finalPoints;

   public Final()
   {
   }

   public java.lang.Double getFinalPoints()
   {
      return this.finalPoints;
   }

   public void setFinalPoints(java.lang.Double finalPoints)
   {
      this.finalPoints = finalPoints;
   }

   public Final(java.lang.Double finalPoints)
   {
      this.finalPoints = finalPoints;
   }

}