package com.vizuri.fhir;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Final implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.Double finalValue;

   public Final()
   {
   }

   public java.lang.Double getFinalValue()
   {
      return this.finalValue;
   }

   public void setFinalValue(java.lang.Double finalValue)
   {
      this.finalValue = finalValue;
   }

   public Final(java.lang.Double finalValue)
   {
      this.finalValue = finalValue;
   }

}