package com.vizuri.fhir;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class PatientAge implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.Integer age;

   public PatientAge()
   {
   }

   public java.lang.Integer getAge()
   {
      return this.age;
   }

   public void setAge(java.lang.Integer age)
   {
      this.age = age;
   }

   public PatientAge(java.lang.Integer age)
   {
      this.age = age;
   }

}