package com.vizuri.fhir;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Points implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.Double pointTotal;

   private java.lang.Double addValue;

   public Points()
   {
   }

   public java.lang.Double getPointTotal()
   {
      return this.pointTotal;
   }

   public void setPointTotal(java.lang.Double pointTotal)
   {
      this.pointTotal = pointTotal;
   }

   public void addPointTotal(java.lang.Double points)
   {
      this.pointTotal += points;
   }

   public java.lang.Double getAddValue()
   {
      return this.addValue;
   }

   public void setAddValue(java.lang.Double addValue)
   {
      this.addValue = addValue;
   }

   public Points(java.lang.Double pointTotal, java.lang.Double addValue)
   {
      this.pointTotal = pointTotal;
      this.addValue = addValue;
   }

}